// Character creation podpeople
/datum/species/pod/get_species_description()
	return "Podpeople are leafy, plant-based humans grown from a Replica Pod Seed mixed with human blood, superficially resembling a hybrid of almost any bipedal humanoid and any photosynthetic plant. Replacing the original person, Podmen are a cheap 'second life' for those who can't afford better. Podmen heal in the light and wilt in the dark, dying in minutes."

/datum/species/pod/get_species_lore()
	return list("https://wiki.novasector13.com/wiki/Lore:Podperson",
		"The fruit of the commercial product \"Replica Pods,\" Pod People are the synthesis of humanoid blood and postmodern cabbage. Fully sentient, with the Resonance and memories of the blood donor, these Plant People are well-suited to life in the limelight. While the modern Replica Pod itself comes from modified cabbage, the end result can superficially resemble a hybrid of almost any bipedal humanoid and any photosynthetic plant. Pod People heal physical injuries when exposed to light, and rapidly wilt in the dark, dying in minutes. Modern Pod People come either from existing persons resurrected via cheap seeds from seed vendors, or as descendants from Colonial Seed Vaults, the terrarium structure randomly found on most mining planets. ",
		"Originally sold as a body replacement solution, Replica Pod people were one of humanity's first forays into post-mortality. The simplicity of combining a sample of blood into a conventionally-grown plant, alongside the potential to delay the harvest for numerous years, meant that even without FTL technology, interstellar colonization could be accessible to the masses.",
		"Humanity's Manifest Destiny reflex triggered a brief boom of mass colonization efforts: every corporation or backyard enthusiast who could afford the meager sum to craft a shelter capable of sustaining a plant would rent time on the neighborhood Mass Driver to catapult their personal homestead into the stars. Sloth and Capitalism go hand-in-hand, so the industry turned towards marketing homestead packages: Four Replica Pods of menial workers would be sent in your place inside a standard-issue Seed Vault, stocked with the cheapest finest sampling of Earth plants. With the directive to \"Spread Life,\" these workers would do the hard work of terraforming \"your\" land into something glorious and habitable. In a century or two, when your family line finally arrives at \"your\" homestead, deed in hand, they will be settling in the lap of luxury. ",

		"Pod People come from one of three sources, typically. An existing person: Typically, a modern spacer dies and chooses to be reborn via a Replica Pod. They contain both the Resonance and memories of that person, and thus likely retain their existing cultural ties and familial relations. The death might not always be accidental, and the rebirth might not always be immediately afterwards. Cautious persons might keep an imprinted Replica Pod seed as a contingency in case other undeath plans fall through.",
		"Random Chance: Rarely a growing Replica Pod just happens to catch a stray Resonance engram and enough stray DNA to be able harvest itself into a fully-sapient individual, with no biological or mental ties to any person who came before.",
		"A Colonial Seed Vault: or descendant thereof. Pod Persons are by default sterile, so the mechanism by which the original four Primal Pod Persons produce additional Pod Persons is left as an exercise for the colonists themselves to resolve. Examples include: the launching company provided a number of blood samples to inject into subsequent harvests of Pod Persons. Mass harvests of Replica Pod plants to \"force\" random chance. Using the provided Biogenerator to print Monkeys, then mix their blood in ways to capture stray souls. Abnormal insterility, rendering pre-fertilized Replica Pod seeds that require no external blood or soul. Strictly speaking, only the original four Primal Pod Persons have the compulsion to \"Spread Life.\" How strongly they impose this directive upon their progeny is up to them.",

		"As Pod People come from an impossibly diverse set of circumstances, their shared culture is based strictly off of innate impulses and shared sensations. Only three tenets are truly universal across all podmen:",
		"The Calling: Plant People feel an innate compulsion to change their name to some sort of plant reference. Often as minor as tweaking their old Human name. Humans with an strong attachment to their human selves have been known to forego this, though it is seen as abhorrent and disrespectful to the renewed gift of life.",
		"The Tongue: Sylvan is spoken natively by anyone made of Nature. The origins of the language are unknown, but as the tongue is instinctual, historians speculate as to a grand cosmic origin of all plant life.",
		"The Light: Stemming from the strict physiological need for light, plant people like light. Plantfolk who work indoors or in space are known to bring their own sources of light. Lanterns, flashlights, glowshrooms, Ethereal boyfriend...",


		"As with all human capitalistic ventures, quality is only guaranteed so long as it can be enforced, and quantity is king. Thousands of these Colonial Gardens were launched from Earth during the early 2100s, fired at any moving body astronomers could be bribed to say had gravity and the ability to sustain an atmosphere. As a result, many Seed Vaults actually landed in invalid locations, if they landed at all, and many planets had dozens of competing Seed Vaults land on their surface, Lavaland and Freya included.",

		"As with all commercial booms, as soon as a better product came to market, the original is cast to obscurity. Replica Pod seeds were seen as mostly inferior to later life-extending technologies, including Genemodding, Artificial Engram collection, and the disastrous direct Human-grown Cloning.",

	)
